### ISSUE TITLE
the advantage over bazil.org/fuse

### ISSUE THREAD

**Issue by iwanbk** [jacobsa/fuse#15]
I saw that bazil.org/fuse appeared in this project's readme.
Can you give some description how this project compared to bazil.org/fuse?

Thanks

**Comment by jacobsa** [comment]
The API is different, in a way that I find easier to work with, and the documentation tends to be a bit more complete. Your mileage may vary; please consult the docs for each and see which you personally prefer. :-)

**Comment by kahing** [comment]
I ported https://github.com/kahing/goofys from this to bazil a while back, and found that my write performance dropped by something like half so I never merged it. I think there was recent work for this on bazil but I haven't rechecked the result.

My initial concern was that there seemed to be more contributors to bazil, and it's hard for me to tell which fuse project will be alive for longer.

**Comment by rucuriousyet** [comment]
Are any benchmarks around for this project? Would be nice to see the actual r/w performance and overhead incurred by this library as opposed to something like bazil or the C fuse implementation. I know that bazil/fuse is known to be very slow...

**Comment by jacobsa** [comment]
I did a bunch of work a couple of years ago to significantly increase the performance of [gcsfuse](https://github.com/googlecloudplatform/gcsfuse), which previously used bazilfuse and now uses this library by making a bunch of speed improvements over what bazilfuse did. If you're interested in artifacts (including benchmarks), see GoogleCloudPlatform/gcsfuse#83 as well as the commits in this repo and that repo around 2017-07-29 or so.

I don't know if bazilfuse has gotten better since then. The primary win of this library in my opinion is that its API is a lot better documented.

**Comment by chrislusf** [comment]
Does this project support multi-thread read and write? I am working on SeaweedFS and using a branched version of bazil.org/fuse. The testing performance indicates there are some bottleneck.

**Comment by stapelberg** [comment]
> Does this project support multi-thread read and write?

Yes: https://github.com/jacobsa/fuse/blob/081e9f4bc7d4b131a4d4a0e4ffa3d76a9c85c4da/fuseutil/file_system.go#L95-L124

Note that for my use-case in https://distr1.org, changing the code to use a single goroutine was a performance win, though. YMMV.
