### ISSUE TITLE
sync_read support

### ISSUE THREAD

**Issue by kahing** [jacobsa/fuse#16]
Currently all the fuse operations are handled in parallel. C-fuse has a `sync_read` option which performs all the reads synchronously, which is useful when the filesystem wants to perform its own readahead, for example.

Ideally this would be per fd.

**Comment by kahing** [comment]
To elaborate a little, because each read currently spawns a goroutine, the filesystem may receive the read operations out of order.

**Comment by jacobsa** [comment]
Are you sure this isn't already the case in this package? It's been awhile since I've looked at the mounting process, but I think it may be.

The `sync_read` option to the C fuse library [appears to cause](https://github.com/fuse4x/fuse/blob/089da12815540559cef7dc89bf66e10e724abd8e/lib/fuse_lowlevel.c#L1690) the `async_read` field of the connection struct to be set to zero. Later in `do_init`, [this will cause](https://github.com/fuse4x/fuse/blob/089da12815540559cef7dc89bf66e10e724abd8e/lib/fuse_lowlevel.c#L1359-L1360) the response to the kernel to not have the `FUSE_ASYNC_READ` flag set. (I can't find any other effect in the interaction with the kernel or the way requests are dispatched locally than this.)

In contrast, this package [never sets](https://github.com/jacobsa/fuse/blob/master/connection.go#L161-L169) the async read flag. In other words, I believe `sync_read` is in effect always on.

**Comment by jacobsa** [comment]
I dug a little bit further and found that yes, I disabled async reads on purpose in 348ed9e731d013c43ea857ac6a9e1330e99faaa0, for exactly the reason you describe. :-)

(For the record, the measurements for gcsfuse that inspired this are recorded in GoogleCloudPlatform/gcsfuse@1d92d3e1ed20aa09227d591568d4c7ac79c1509e and GoogleCloudPlatform/gcsfuse@babd4214d43691d54a6d240560c93d428bb319d2.)

**Comment by kahing** [comment]
sorry forgot to respond. I wasn't able to reproduce the original problem anymore and this could be a problem on my side. Closing.
