### ISSUE TITLE
Sync filesystem operation

### ISSUE THREAD

**Issue by orodeh** [jacobsa/fuse#71]
Are there any plans to support the sync filesystem operation? I need to to force the filesystem to upload all dirty files that it has. The unmount operation doesn't wait for this to happen, unfortunately.

**Comment by jacobsa** [comment]
There is already [an op](https://godoc.org/github.com/jacobsa/fuse/fuseops#SyncFileOp) sent by fuse on behalf of fsync(2).

**Comment by orodeh** [comment]
Sure, but that is an `fsync`, which is for a single file. I am talking about `sync` which is for all files with dirty data. The user could, potentially, keep track of such files on his own. However, that is a global property requiring synchronization between all processes using the filesystem.

**Comment by jacobsa** [comment]
Sorry, I see. As far as I can tell, the kernel fuse interface [has no opcode](https://github.com/torvalds/linux/blob/e36cb0b89ce20b4f8786a57e8a6bc8476f577650/include/uapi/linux/fuse.h#L317-L364) corresponding to sync(2). You'd have to research what that actually turns into at the VFS layer. It's possible that you actually do get an fsync op for each dirty file, which would make sense because the kernel is already tracking what's dirty.

**Comment by orodeh** [comment]
Thanks, I didn't realize that FUSE didn't see the `sync` operations. I will look at the `fsync` more carefully.
