### ISSUE TITLE
Shared mmap mapping results in -EACCES or -ENODEV

### ISSUE THREAD

**Issue by orodeh** [jacobsa/fuse#82]
Mmap currently does not work on Linux because the opcodes 39 and 40 aren't supported. These are defined in `fuse_kernel.go`, but not implemented. 

To reproduce the problem you can do the following:
```
>>> import mmap
>>> fd = open('README.md', 'r')
>>> mmap.mmap(fd.fileno(), 0, mmap.PROT_READ)
```
This results in a `Permission denied`, or `No such device` error. 

The interesting twist is that this does work if the mapping is private. 

```
mmap.mmap(fd.fileno(), 0, prot=mmap.PROT_READ, flags=mmap.MAP_PRIVATE, offset=0)
```

**Comment by orodeh** [comment]
We are using jacobsa in our [dxfuse filesystem](https://github.com/dnanexus/dxfuse). It has been working very well.

**Comment by stapelberg** [comment]
I think you’re reading this wrong :)

OpCode 39 and 40 are ioctl and poll, respectively.

When running `fd = open('/ro/vim-amd64-8.1-4/out/share/man/man1/evim.1', 'r')`, Python does:

```
openat(AT_FDCWD, "/ro/vim-amd64-8.1-4/out/share/man/man1/evim.1", O_RDONLY|O_CLOEXEC) = 4</ro/vim-amd64-8.1-4/out/share/man/man1/evim.1>
fstat(4</ro/vim-amd64-8.1-4/out/share/man/man1/evim.1>, {st_dev=makedev(0, 0xd7), st_ino=122441614869140632, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=3, st_size=1375, st_atime=1585994604 /* 2020-04-04T12:03:24+0200 */, st_atime_nsec=0, st_mtime=1585994604 /* 2020-04-04T12:03:24+0200 */, st_mtime_nsec=0, st_ctime=1585994604 /* 2020-04-04T12:03:24+0200 */, st_ctime_nsec=0}) = 0
ioctl(4</ro/vim-amd64-8.1-4/out/share/man/man1/evim.1>, TCGETS, 0x7ffe85449040) = -1 ENOSYS (Function not implemented)
lseek(4</ro/vim-amd64-8.1-4/out/share/man/man1/evim.1>, 0, SEEK_CUR) = 0
ioctl(4</ro/vim-amd64-8.1-4/out/share/man/man1/evim.1>, TCGETS, 0x7ffe85448f80) = -1 ENOSYS (Function not implemented)
```

That’s where the ioctl requests come from.

When doing the mmap call, the FUSE daemon gets no requests. This is because shared mmap mappings are not supported by the Linux kernel with FUSE: https://elixir.bootlin.com/linux/v5.6/source/fs/fuse/file.c#L2306

Hence, there’s nothing we can do in this library.

**Comment by orodeh** [comment]
Thanks, that is a very informative explanation.
