### ISSUE TITLE
Would you tell me fuseops error messages in detail ?

### ISSUE THREAD

**Issue by seinocluster2** [jacobsa/fuse#90]
Hi,

I want to investigate the cause of errors.
I use goofys.
goofys include fuseops packeges.

The following error messages often output to the log file.

1. fuse.ERROR *fuseops.ReadFileOp error: no such file or directory
2. fuse.ERROR *fuseops.RemoveXattrOp error: operation not permitted

Would you tell me the document related to error messages ?

**Comment by stapelberg** [comment]
I would recommend to enable debug logging in goofys.

See this example for how to enable debug logging: https://github.com/distr1/distri/blob/f4148dc779384bafb86eeb8e10ef7a8d276fdae9/internal/fuse/fuse.go#L253

That should allow you to understand what your file system is doing wrong.

In general, search for Linux kernel or FUSE instead of the specific jacobsa/fuse implementation.
